version: '3.8'
services:
  skillaro:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  
  postgres:
    container_name: next_postgres
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=gateway.docker.internal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12qwaszx
      - POSTGRES_DB=skillaro_database_development
    ports:
      - 5432:5432

networks:
  stagingnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16
          gateway: 192.168.29.1
