version: '3.8'
services:
  skillaro:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 12qwaszx
      DB_NAME: skillaro_database_development
    depends_on:
      - db
    links:
      - db
    volumes:
      - './:/app'
      - /app/node_modules
      - /app/.next
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12qwaszx
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
